### PR TITLE
Fix syntax to be compatible with Tensorflow v1.0

### PR DESCRIPTION
**Pull request by resonatevision**
Remove deprecated function calls.

### CODE REVIEW

**Comment by asanakoy** [comment]
@resonatevision, thanks for the pull request! 
Have you tested the changes?

**Comment by resonatevision** [comment]
Yes. Tested on Tensorflow 1.0.1. 
Couldn't get the training to run without the changes. Also, there were some WARNINGS about the deprecating apis this month so I changed those too.

**Comment by resonatevision** [comment]
Actually I am having trouble with chainer now. Don't know if it is related to the changes I made to global counter. It gives me I/O error in self._invoke_prefetch() when evaluate_pcp is called. Could be completely different issue. But you can hold off on merging if you have never seen this before.
Update: I reverted back the global variable changes. Still seeing the evaluate_pcp problem. It's something else. Any thoughts?

**Comment by asanakoy** [comment]
This is not related, I think. 
As far as I remember your problem is related to chainer multi-threading.

**Comment by resonatevision** [comment]
Yes. Exactly. Any thoughts on how you solved it?

**Comment by resonatevision** [comment]
I fixed it by replacing the MultiprocessIterator with SerialIterator. Obviously will impact training speed but that's the best I could do for now.

**Comment by asanakoy** [comment]
Sorry, I'm quiet busy now with other project, but I will check your pull request and your problem in 2 weeks :)

**Comment by asanakoy** [comment]
I upgraded to tensorflow r1.0 using script provided with tensorflow.

**Pull request closed without merging**
